# Generated by Django 5.0.3 on 2024-04-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('field', models.CharField(max_length=32)),
                ('affiliation', models.CharField(max_length=10000)),
                ('score', models.IntegerField()),
                ('pub_count', models.IntegerField()),
                ('coauthorship_count', models.IntegerField()),
                ('yoe', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KolPubList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('article_title', models.CharField(max_length=1000)),
            ],
        ),
    ]
